Add demo app for all desktops and instructions for bootstrapping
DavBfr/dart_pdf pull request #1165
Opened 2022-10-10 03:29 UTC by HankG

This commit added platform projects for Windows and Linux for the built-in demo project. These platforms were tested under Linux Mint and Windows 10 running the latest Flutter SDK.

This commit also adds additional information to the README files in the pdf and demo project to point developers to the existence of the demo project. I honestly didn't realize there was such a detailed implementation in this repository. This would elevate this to the front of the pub.dev page as well as within this repository.

2022-10-10 04:51 UTC, DavBfr commented on demo/README.md
> +flutter run -d linux
macos?

2022-10-10 12:49 UTC, DavBfr requested changes
A real dedicated application icon would be nice, instead of the default flutter.
I can also add the required authorization bits for iOS and macOS.

2022-10-10 12:49 UTC, DavBfr commented on demo/android/app/src/main/kotlin/net/nfet/demo/MainActivity.kt
> +package net.nfet.demo
I'd prefere `printing_demo` as in the pubspec.yaml
Same everywhere else.

2022-10-17 13:36 UTC, HankG commented
These latest updates to the demo app address:

- Removed the new Kotlin file which was autogenerated and unneeded
- Remove the default widget_test.dart file which was not being used and had compile time errors
- Add the print entitlement to the release macOS project. As far as I can tell that was the only missing config for enabling printing across the platforms. If there are more I can tweak the library documentation to make it more clear what is needed.

2022-10-22 12:42 UTC, DavBfr commented
Merged, thanks.

2022-10-22 12:42 UTC, closed without merging