PDF/A 3b
DavBfr/dart_pdf pull request #1750
Opened 2024-09-27 08:50 UTC by ilaurillard

Would you please have a look at the catalog.dart file - there is a problem with the "/Names" part.
You have an indirect/ref field and i have a "PdfDict" - these have to be merged somehow ..

greetings

2024-09-27 20:16 UTC, DavBfr requested changes

2024-09-27 20:16 UTC, DavBfr commented on pdf/lib/src/pdf/obj/pdf_a_3b.dart
Perhaps this file could be divided into multiple class files.

2024-09-27 20:16 UTC, DavBfr commented on pdf/lib/src/pdf/obj/catalog.dart
> +      params['/Names'] = attached!.catalogNames();
If names already exists, just merge the dict here.

```dart
if (params.containsKey('/Names')) {
  params['/Names']!.merge(attached!.catalogNames());
} else {
  params['/Names'] = attached!.catalogNames();
}
```

2024-09-29 10:29 UTC, ilaurillard commented on pdf/lib/src/pdf/obj/annotation.dart
> +    else {
ok, made attribute in base class non nullable - without changing derived classes - we need to make this late final, or?

2024-09-29 10:29 UTC, ilaurillard commented on pdf/lib/src/pdf/obj/pdf_a_3b.dart
ok, done

2024-09-29 10:30 UTC, ilaurillard commented on pdf/lib/src/pdf/obj/catalog.dart
> +      params['/Names'] = attached!.catalogNames();
since names is a ref, i know merge the pdfa-names into the pdfNames .. ok?

2024-09-30 10:41 UTC, grundid commented
@ilaurillard Thank you for your pdf/a implementation. I see you have added some code related to XRechnung/Factur-X. I'm also working on an implementation for e-invoices.
Could you please make ```PdfaFacturxRdf``` more customizable? 
It should be possible to set the ```ConformanceLevel``` and not only fix it to "BASIC".

At the same it might be better to put this code in a separated library as it is more related to e-invoices than generic PDF generation. I could provide my schema dart code for e-invoices.

2024-09-30 15:06 UTC, ilaurillard commented
> @ilaurillard Thank you for your pdf/a implementation. I see you have added some code related to XRechnung/Factur-X. I'm also working on an implementation for e-invoices. Could you please make `PdfaFacturxRdf` more customizable? It should be possible to set the `ConformanceLevel` and not only fix it to "BASIC".
> 

done

> At the same it might be better to put this code in a separated library as it is more related to e-invoices than generic PDF generation. I could provide my schema dart code for e-invoices.

yes, you are right..  pdf/a and e-invoices are separate things ... 
this should be discussed .. @DavBfr?

@grundid  for UBL invoices i wrote a class generator, that crawls the official xsd schemas an makes dart classes of the definitions, if you are interested ..

2024-10-01 06:53 UTC, grundid commented
> @grundid for UBL invoices i wrote a class generator, that crawls the official xsd schemas an makes dart classes of the definitions, if you are interested ..

Well, yes! Right now I've done the same thing for the ZUGFeRD specification in Germany and now I'm validating the output xml agains the schematron rules. 
Shall we set up a project and discuss collaboration?

2024-10-05 12:35 UTC, DavBfr commented
Yes, all schema generation could be in another package.

2024-10-08 09:44 UTC, grundid commented
I've created a dart package dedicated to the creation of e-invoices based on the ZUGFeRD/Factur-X specification: https://github.com/Blaulichtplaner/e_invoice_tools

@ilaurillard you can find an example with all the schema classes here:
https://github.com/Blaulichtplaner/e_invoice_tools/blob/main/packages/e_invoice_data_classes/example/e_invoice_data_classes_example.dart

2024-11-26 15:12 UTC, CLNMR commented on pdf/lib/src/pdf/obj/pdfa/README.md
> +4. You muss include a Colorprofile, use the below "PdfaColorProfile" and embed the contents of "sRGB2014.icc"
```suggestion
4. You must include a Colorprofile, use the below "PdfaColorProfile" and embed the contents of "sRGB2014.icc"
```

2024-11-26 15:15 UTC, CLNMR commented
Hi, is there any timeline when this could be merged? I need the capability to attach files (xml-documents) to my pdf to create a valid ZUGFeRD document :)

2024-11-26 20:44 UTC, DavBfr approved these changes

2024-11-28 10:54 UTC, merged