Adding Additional Annotation Support
DavBfr/dart_pdf pull request #742
Opened 2021-06-30 19:22 UTC by johncharris

I'm working on more complete annotation support. I ran into an issue I'm unsure of.

Where is the best place to add the appearance? I added a method to do this, but I think there is a better way.

Once I get feedback on this I'll add more types of annotations.

2021-06-30 19:45 UTC, DavBfr requested changes
Please run `make format` to reformat all the code.
or `dart format --fix .` if you can't run the Makefile.

2021-06-30 19:45 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +  AnnotationUrl(this.destination, {this.date, this.subject, this.author});
Can you add a comma after `this.author`?

2021-06-30 19:57 UTC, DavBfr requested changes

2021-06-30 19:57 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +  void addAppearance() {
I think you should not have this here, see the other comment on AnnotationPolygon

2021-06-30 19:57 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +  AnnotationPolygon(this.points, {this.color, this.interiorColor, this.border, this.date, this.subject, this.author});
To keep the Flutter spirit of Widgets, the polygon drawing should be a child widget.
A Polygon widget will get the same List<PdfPoint> on its constructor and will just draw. It can be used outside the AnnotationPolygon with more settings, maybe a ClipPolygon widget can be interesting to clip its child, this child can be used to draw anything else within the defined annotation.
What do you think?

2021-06-30 23:01 UTC, johncharris commented on pdf/lib/src/widgets/annotations.dart
> +  AnnotationPolygon(this.points, {this.color, this.interiorColor, this.border, this.date, this.subject, this.author});
For proper PDF compatibility it should be use the different annotation subtypes Polygon, Polyline, Ink, etc.

That said, I had issues rendering the polygon annotation without the stream. Notably, PDF.js has issues with this [6810](https://github.com/mozilla/pdf.js/issues/6810).

My preference would be to do it by the book for the most compatibility. I like the idea of having some drawing widgets the convert into streams. I haven't looked too see what this library has for that.

2021-06-30 23:02 UTC, johncharris commented on pdf/lib/src/pdf/annotation.dart
> +  void addAppearance() {
Were is the best place to run the code that will make the appearance stream? I agree this isn't it.

2021-07-01 10:05 UTC, DavBfr requested changes

2021-07-01 10:05 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +  void addAppearance() {
You can remove the appearance code from here, and add it to the Widget AnnotationPolygon as a child widget.

Same as PdfButtonField => FlatButton. Basically everything in lib/src/pdf is low-level dumb PDF, and lib/src/widgets is what developers expect for an easy-to-use API.

2021-07-01 10:05 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +  AnnotationPolygon(this.points, {this.color, this.interiorColor, this.border, this.date, this.subject, this.author});
Look at the Signature Widget: it draws its child into an appearance stream.

2021-07-03 11:40 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +          subtype: '/InkList',
I don't see this annotation type in the PDF documentation. Only Ink which has an InkList key.

2021-07-03 11:40 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +            child: Rectangle(
What about having this:
```dart
SquareAnnotation({
...
  Widget? child,
  }) : super(
            child: child ?? Rectangle(...),
            builder: ...
```

2021-07-03 17:53 UTC, DavBfr requested changes

2021-07-03 17:53 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +            child: InkList(
Could be replaced by a list of Polygons

2021-07-03 17:53 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +class PolyLineAnnotation extends Annotation {
Why not reuse Polygon with a `closed` parameter?

2021-07-06 10:59 UTC, DavBfr requested changes

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +        context.localToGlobal(PdfRect(minX, minY, maxX - minX, maxY - maxX));
maxY - maxX?

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            author: author);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +    params['/Vertices'] =
If `/SubType` is `Ink` this will be `/InkList`

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +class PdfAnnotInkList extends PdfAnnotBase {
Can you rename this to `PdfAnnotInk`?

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +class AnnotationInkList extends AnnotationBuilder {
Can you rename this to `AnnotationInk`?

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/pdf/annotation.dart
> +            subtype: closed ? "/PolyLine" : '/Polygon',
Please use single quotes.

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +          subject: subject),
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +          subject: subject),
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +        subject: subject);
missing comma

2021-07-06 10:59 UTC, DavBfr commented on pdf/lib/src/widgets/annotations.dart
> +          subject: subject),
missing comma

2021-07-22 16:13 UTC, DavBfr commented
Merged, thanks.

2021-07-22 16:13 UTC, closed without merging